# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

set -o vi	
umask 0027	

# aliases 
alias 'mplayer'='mplayer -vo caca'
alias 'puppet-lint'='puppet-lint --no-80chars-check'
